apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-08-09T22:32:09Z"
  generateName: ungaged-salamander-insikt-jenkins-qa-deployer-79d6dcc8dd-
  labels:
    app: insikt-jenkins-qa-deployer
    appType: helm
    pod-template-hash: "3582877488"
    release: ungaged-salamander
  name: ungaged-salamander-insikt-jenkins-qa-deployer-79d6dcc8dd-kmcs9
  namespace: env-3vo8v0rs
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ungaged-salamander-insikt-jenkins-qa-deployer-79d6dcc8dd
    uid: 39710b98-baf4-11e9-9b3b-0aa95c0a58a2
  resourceVersion: "39101971"
  selfLink: /api/v1/namespaces/env-3vo8v0rs/pods/ungaged-salamander-insikt-jenkins-qa-deployer-79d6dcc8dd-kmcs9
  uid: 8697fa15-baf5-11e9-9b3b-0aa95c0a58a2
spec:
  containers:
  - env:
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: TILLER_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: JAVA_OPTS
      value: -Djenkins.install.runSetupWizard=false
    - name: JENKINS_HOME
      value: /vol/jenkins_home
    - name: JENKINS_USER_HOME
      value: /var/jenkins_home
    - name: JOBS_CONFIG_PATH
      value: /var/insikt-qa-jenkins-deployer-jobs-config
    - name: S3_CHARTS_REPO
      value: s3://insikt-charts-repo/
    - name: GIT_SSH
      value: /vol/jenkins_home/.ssh
    image: 175271039525.dkr.ecr.us-west-2.amazonaws.com/insikt-job-scheduler:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 8080
      timeoutSeconds: 1
    name: insikt-jenkins-qa-deployer
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 15
      periodSeconds: 30
      successThreshold: 1
      tcpSocket:
        port: 8080
      timeoutSeconds: 1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /vol
      name: insikt-jenkins-qa-deployer-vol
    - mountPath: /var/insikt-qa-jenkins-deployer-jobs-config
      name: jobs-config
      readOnly: true
    - mountPath: /vol/jenkins_home/config.xml
      name: jenkins-config-secrets
      readOnly: true
      subPath: config.xml
    - mountPath: /vol/jenkins_home/credentials.xml
      name: jenkins-config-secrets
      readOnly: true
      subPath: credentials.xml
    - mountPath: /vol/jenkins_home/jenkins.CLI.xml
      name: jenkins-config-secrets
      readOnly: true
      subPath: jenkins.CLI.xml
    - mountPath: /vol/jenkins_home/jenkins.plugins.slack.SlackNotifier.xml
      name: jenkins-config-secrets
      readOnly: true
      subPath: jenkins.plugins.slack.SlackNotifier.xml
    - mountPath: /var/jenkins_home/.aws/credentials
      name: jenkins-config-secrets
      readOnly: true
      subPath: credentials
    - mountPath: /vol/jenkins_home/secrets/master.key
      name: jenkins-config-secrets
      readOnly: true
      subPath: master.key
    - mountPath: /vol/jenkins_home/secrets/hudson.util.Secret
      name: jenkins-config-secrets
      readOnly: true
      subPath: hudson.util.Secret
    - mountPath: /etc/profile.d/insikt-git.sh
      name: git-config-secrets
      readOnly: true
      subPath: insikt-git.sh
    - mountPath: /var/.ansible
      name: ansible-vault-password
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: insikt-helm-deployer-sa-token-dslnn
      readOnly: true
  dnsPolicy: ClusterFirst
  initContainers:
  - args:
    - -c
    - cd /vol && mkdir -p {jenkins_home/jobs/reload-config,charts/repo} && chown -R
      1000:1000 {jenkins_home,charts}
    command:
    - /bin/sh
    image: 175271039525.dkr.ecr.us-west-2.amazonaws.com/insikt-base:latest
    imagePullPolicy: IfNotPresent
    name: insikt-jenkins-qa-deployer-permission-init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /vol
      name: insikt-jenkins-qa-deployer-vol
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: insikt-helm-deployer-sa-token-dslnn
      readOnly: true
  nodeName: ip-10-0-1-133.us-west-2.compute.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: insikt-helm-deployer-sa
  serviceAccountName: insikt-helm-deployer-sa
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: insikt-jenkins-qa-deployer-vol
    persistentVolumeClaim:
      claimName: env-3vo8v0rs-qa-jenkins-helmdeployer01
  - name: ansible-vault-password
    secret:
      defaultMode: 420
      secretName: insikt-ansible-vault-secrets
  - name: jenkins-config-secrets
    secret:
      defaultMode: 420
      items:
      - key: jenkins-credentials.xml
        path: credentials.xml
      - key: jenkins-config.xml
        path: config.xml
      - key: jenkins.CLI.xml
        path: jenkins.CLI.xml
      - key: jenkins-hudson.util.Secret
        path: hudson.util.Secret
      - key: jenkins-master.key
        path: master.key
      - key: jenkins.plugins.slack.SlackNotifier.xml
        path: jenkins.plugins.slack.SlackNotifier.xml
      - key: s3-charts-repo-credentials
        path: credentials
      secretName: insikt-qa-jenkins-deployer-config-secrets
  - name: git-config-secrets
    secret:
      defaultMode: 420
      items:
      - key: insikt-git.sh
        path: insikt-git.sh
      secretName: insikt-git-sync-config-secrets
  - configMap:
      defaultMode: 420
      name: insikt-qa-jenkins-deployer-jobs-config-cm
    name: jobs-config
  - name: insikt-helm-deployer-sa-token-dslnn
    secret:
      defaultMode: 420
      secretName: insikt-helm-deployer-sa-token-dslnn
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-08-09T22:32:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-08-09T22:34:09Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-08-09T22:32:09Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://10649f87356aab4599bbba4f41d46d7f39be86818b344e2690dda1adf138e351
    image: 175271039525.dkr.ecr.us-west-2.amazonaws.com/insikt-job-scheduler:latest
    imageID: docker-pullable://175271039525.dkr.ecr.us-west-2.amazonaws.com/insikt-job-scheduler@sha256:eca492a42949fd33ea9dfa0ff75698ed838ad7c7b68796d0aeff8efcbfa13c44
    lastState: {}
    name: insikt-jenkins-qa-deployer
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-08-09T22:33:30Z"
  hostIP: 10.0.1.133
  initContainerStatuses:
  - containerID: docker://7daf73d30f9da444a8100c96a4a4f4181e8f2aed26ca991716e2ba52d440a16e
    image: 175271039525.dkr.ecr.us-west-2.amazonaws.com/insikt-base:latest
    imageID: docker-pullable://175271039525.dkr.ecr.us-west-2.amazonaws.com/insikt-base@sha256:02ae9b65c234075a3b21891e0ffec5e05e94b2838c427ccb7478bf95b6e1d1a1
    lastState: {}
    name: insikt-jenkins-qa-deployer-permission-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://7daf73d30f9da444a8100c96a4a4f4181e8f2aed26ca991716e2ba52d440a16e
        exitCode: 0
        finishedAt: "2019-08-09T22:32:43Z"
        reason: Completed
        startedAt: "2019-08-09T22:32:43Z"
  phase: Running
  podIP: 10.0.1.93
  qosClass: Burstable
  startTime: "2019-08-09T22:32:09Z"
